name: Publish

on:
  release:
    types: [ published ]

jobs:
  build:
    runs-on: windows-latest
    
    env:
      name: "DragonFruit.Link"
      project: "DragonFruit.Link\\DragonFruit.Link.csproj"

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PowerShell Policy
        run: Set-ExecutionPolicy -ExecutionPolicy Unrestricted -Force
        
      - name: Install .NET 6
        run: choco install dotnet-sdk
        
      - name: Download Publish Script
        run: powershell Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dragonfruitnetwork/publish-script/main/nuget.ps1" -OutFile ".\nuget.ps1"

      - name: NuGet Build and Publish (Release)
        run: .\nuget.ps1 -TargetName $env:name -TargetProject $env:project -ApiKey ${{ secrets.NUGET_KEY }}
        if: "!github.event.release.prerelease"

      - name: Nuget Build and Publish (Beta)
        run: .\nuget.ps1 -TargetName $env:name -TargetProject $env:project -ApiKey ${{ secrets.NUGET_KEY }} -Suffix "-beta"
        if: "github.event.release.prerelease"
